### ISSUE TITLE
Tópicos Setembro/2023

### ISSUE THREAD

**Issue by lorenzolfm** [saopaulobitdevs/saopaulobitdevs.org#12]

**Comment by lorenzolfm** [comment]
https://utxo.live/oracle/

**Comment by lorenzolfm** [comment]
https://lexe.app/

**Comment by lorenzolfm** [comment]
https://bolt.fun/tournaments/legends-of-lightning-vol2/overview?ref=nobsbitcoin.com

**Comment by lorenzolfm** [comment]
https://twitter.com/River/status/1704138775994265982

**Comment by lorenzolfm** [comment]
https://www.nobsbitcoin.com/zeus-v0-8-0-alpha-opened-to-waitlist-subscribers/

**Comment by lorenzolfm** [comment]
https://zerosync.org/demo/

**Comment by lorenzolfm** [comment]
https://ambosstech.medium.com/businesses-meet-hydro-your-new-best-friend-for-lightning-network-payments-d9fb90016e67

**Comment by lorenzolfm** [comment]
https://github.com/thesimplekid/cashu-lnurl

**Comment by lorenzolfm** [comment]
https://www.nobsbitcoin.com/paxos-identified-as-fat-finger-entity-in-20-btc-fee-mistake/

**Comment by lorenzolfm** [comment]
https://bitcoinmagazine.com/technical/op-checkseparatesig-and-actuaries-fixing-multiparty-channel-factories

**Comment by lorenzolfm** [comment]
https://github.com/tee8z/doppler

**Comment by lorenzolfm** [comment]
https://github.com/bitcoin/bips/pull/1489

**Comment by lorenzolfm** [comment]
https://gist.github.com/instagibbs/1d02d0251640c250ceea1c66665ec163

**Comment by lorenzolfm** [comment]
https://twitter.com/jamesob/status/1704869752470921302

**Comment by oleonardolima** [comment]
https://obscuravpn.io/
