### ISSUE TITLE
Topicos Dezembro

### ISSUE THREAD

**Issue by lorenzolfm** [saopaulobitdevs/saopaulobitdevs.org#16]

**Comment by lorenzolfm** [comment]
Swan privacy update

https://www.nobsbitcoin.com/swan-bitcoin-privacy-update/

**Comment by lorenzolfm** [comment]
Blixt v0.6.9
https://github.com/hsjoberg/blixt-wallet/releases/tag/v0.6.9

**Comment by lorenzolfm** [comment]
Sparrow v1.8.0
https://github.com/sparrowwallet/sparrow/releases/tag/1.8.0

**Comment by lorenzolfm** [comment]
Buy eSIMs via LN
https://www.lnesim.com/

**Comment by lorenzolfm** [comment]
Mailing list sunsetting
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2023-November/022134.html

**Comment by lorenzolfm** [comment]
HTLC aggregation with covenants

https://lists.linuxfoundation.org/pipermail/lightning-dev/2023-October/004181.html

**Comment by lorenzolfm** [comment]
Durabit - A Bitcoin-native Incentive Mechanism for Data Distribution
https://github.com/4de67a207019fd4d855ef0a188b4519c/Durabit/blob/main/Durabit%20-%20A%20Bitcoin-native%20Incentive%20Mechanism%20for%20Data%20Distribution.pdf

**Comment by lorenzolfm** [comment]
Fee Estimator updates from Validation Interface/CScheduler thread

https://github.com/bitcoin/bitcoin/pull/28368

**Comment by lorenzolfm** [comment]
bitcoin core v26.0rc-2
https://bitcoincore.org/bin/bitcoin-core-26.0/

**Comment by lorenzolfm** [comment]
BitEscrow: Non-Custodial Escrow for Bitcoin Transactions
https://www.nobsbitcoin.com/bitescrow-beta-launched/

**Comment by lorenzolfm** [comment]
85% Of Whirlpool Users are using self-custodial solutions
https://www.nobsbitcoin.com/85-of-whirlpool-users-are-using-self-hosted-solutions/

**Comment by lorenzolfm** [comment]
Mutiny Wallet adds Onion Message support
https://www.nobsbitcoin.com/mutiny-wallet-v0-4-28/

**Comment by lorenzolfm** [comment]
Kollider is shutting down
https://www.nobsbitcoin.com/kollider-is-shutting-down/

**Comment by MPins** [comment]
Replacement Cycling Attacks on the Lightning Network

https://github.com/ariard/mempool-research/blob/2023-10-replacement-paper/replacement-cycling.pdf

https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2023-October/021999.html

**Comment by a-moreira** [comment]
já discutimos em alguma edição sobre o fato de recentemente de >50% transações (às vezes mais) serem de ordinals? o tópico é polêmico e acho que pode gerar debates interessantes.

**Comment by a-moreira** [comment]
STARK proofs for BitVM execution:
https://github.com/neocarmack/STARK/blob/main/STARK%20proof%20for%20BitVM%20circuit%20execution.pdf

**Comment by jaonoctus** [comment]
https://twitter.com/sunitram/status/1726263927783452955

https://github.com/bitcoin/bitcoin/pull/28913

**Comment by jaonoctus** [comment]
sha256 function for bitvm

https://twitter.com/super_testnet/status/1726772975544807913

**Comment by jaonoctus** [comment]
miningpool-observer project recently reported six OFAC-sanctioned transactions as missing from blocks

https://twitter.com/0xB10C/status/1726964430460588201

**Comment by lorenzolfm** [comment]
Opcodes explained
https://opcodeexplained.com/opcodes/

**Comment by oleonardolima** [comment]
BBQr: Better Bitcoin QR

_Coinkite proposed BBQr protocol and is looking for feedback. BBQr encodes larger files into a series of QR codes so they can cross air gaps._

https://www.nobsbitcoin.com/bbqr-better-bitcoin-qr/

**Comment by oleonardolima** [comment]
bdk-ffi v1.0.0-alpha.2a release
https://github.com/bitcoindevkit/bdk-ffi/releases/tag/v1.0.0-alpha.2a

**Comment by plebhash** [comment]
@a-moreira 
> já discutimos em alguma edição sobre o fato de recentemente de >50% transações (às vezes mais) serem de ordinals? o tópico é polêmico e acho que pode gerar debates interessantes.


@jaonoctus 
> miningpool-observer project recently reported six OFAC-sanctioned transactions as missing from blocks
> 
> https://twitter.com/0xB10C/status/1726964430460588201


a pool nova do `Luke-jr` censurando inscriptions ta jogando lenha nessa fogueira 🔥
https://twitter.com/sethforprivacy/status/1730048309622886827?t=_HYPzs8g8kpF9VA0ZXFidA

**Comment by oleonardolima** [comment]
IPv6 Bitcoin-Certified Addresses

_[...] In this paper, we present Bitcoin-Certified Addresses (BCA), a new technique to bind IPv6 addresses to hosts' public keys. BCA reduces the computational cost of generating addresses by using the PoW computed by Bitcoin nodes to secure the binding. Compared to CGA, BCA provides better protection against spoofing attacks and improves the privacy of hosts. Due to the decentralized nature of the Bitcoin network, BCA avoids reliance on a trusted authority, similar to CGA. BCA shows how the PoW computed by Bitcoin nodes can be reused, which saves costs for hosts and makes Bitcoin mining more efficient._

https://arxiv.org/abs/2311.15842
