### ISSUE TITLE
Topicos Janeiro

### ISSUE THREAD

**Issue by lorenzolfm** [saopaulobitdevs/saopaulobitdevs.org#17]

**Comment by jaonoctus** [comment]
- webhooks no LNURL payRequest, [tweet1](https://twitter.com/jaoNoctus/status/1741166286753677535), [tweet2](https://twitter.com/jaoNoctus/status/1741171754737848512)

**Comment by Davidson-Souza** [comment]
- Deprecating `libbitcoinconsensus` [pr](https://github.com/bitcoin/bitcoin/pull/29189#event-11421036771)
- Musig2 na secp256k1 [pr](https://github.com/bitcoin-core/secp256k1/pull/1479)
- [NIP96](https://github.com/nostr-protocol/nips/blob/master/96.md) mergeada (mais fácil rodar seu próprio file hosting pro nostr)
- [CSFS](https://github.com/bitcoin/bips/pull/1535)
- [https://github.com/bitcoin/bips/pull/1534](Add bip-internalkey)
- [OP_CHECKTEMPLATEVERIFY, OP_CHECKSIGFROMSTACK(VERIFY), OP_INTERNALKEY validation](https://github.com/bitcoin/bitcoin/pull/29198)
- [secp256k1 v0.4.1](https://github.com/bitcoin-core/secp256k1/releases/tag/v0.4.1)
- [BIP352 na libsecp](https://github.com/bitcoin-core/secp256k1/pull/1471)
- [Scaling Lightning Safely With Feerate-Dependent Timelocks](https://lists.linuxfoundation.org/pipermail/lightning-dev/2023-December/004254.html)
- [V3 Transactions are still vulnerable to significant tx pinning griefing attacks](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2023-December/022211.html)

**Comment by MPins** [comment]
https://github.com/bitcoin/bitcoin/pull/28349

C++20 allows to write safer code, because it allows to enforce more stuff at compile time (constinit, conteval, constexpr, std::span, ...).

**Comment by storopoli** [comment]
https://www.nobsbitcoin.com/bitwise-will-donate-10-of-etf-profits-for-bitcoin-development/

Alguns ETFs aprovados vao doar parte do lucro para Bitcoin FOSS Grants

**Comment by lorenzolfm** [comment]
Quantum Cats behind the scenes

https://twitter.com/rot13maxi/status/1745983083608789345

**Comment by lorenzolfm** [comment]
Fiat link

https://medium.com/breez-technology/introducing-fiatlink-a-lightning-fiat-standard-68ab380febb2

**Comment by lorenzolfm** [comment]
Mercury Layer release

https://mercurylayer.com/

**Comment by lorenzolfm** [comment]
Phoenix adiciona "Request inbound liquidity" feature
https://nitter.net/PhoenixWallet/status/1735699451770032354#m

**Comment by lorenzolfm** [comment]
PR pra permitir aritmetica de 64 bits no bitcoin

https://delvingbitcoin.org/t/64-bit-arithmetic-soft-fork/397/3

**Comment by lorenzolfm** [comment]
LNHahcne bips and implementations

https://delvingbitcoin.org/t/lnhance-bips-and-implementation/376
