### ISSUE TITLE
Topicos Maio 2024

### ISSUE THREAD

**Issue by lorenzolfm** [saopaulobitdevs/saopaulobitdevs.org#27]
Issue para sugestao de topicos pro encontro de Maio.

Por favor incluam suas sugestoes no seguinte formato para facilitar a vida dos editores:

**Comment by lorenzolfm** [comment]
zkSnacks descontinuando o servico de coordenacao de Coinjoin

https://blog.wasabiwallet.io/zksnacks-is-discontinuing-its-coinjoin-coordination-service-1st-of-june

**Comment by johnnyasantoss** [comment]
ECash: Rascunho de NUT para distribuição de recompensa de pools de mineração usando blind sigs
https://github.com/plebemineira/nuts/blob/nut-pool/X.md

**Comment by storopoli** [comment]
BOLT12 Available in LDK: https://lightningdevkit.org/blog/bolt12-has-arrived/

**Comment by lorenzolfm** [comment]
libsecp256k1 v0.5
https://github.com/bitcoin-core/secp256k1/blob/master/CHANGELOG.md#050---2024-05-06

**Comment by lorenzolfm** [comment]
Emesbee - Coinjoins with no coordinator

https://stacker.news/items/529905

**Comment by oleonardolima** [comment]
Mining Development Kit is heading to Beta
https://www.mining.build/mdk-beta/

**Comment by oleonardolima** [comment]
[bitcoindev] Signing a Bitcoin Transaction with Lamport Signatures (no changes needed)

https://bitcoinops.org/en/newsletters/2024/05/08/#consensus-enforced-lamport-signatures-on-top-of-ecdsa-signatures

https://mailing-list.bitcoindevs.xyz/bitcoindev/CAEM=y+XyW8wNOekw13C5jDMzQ-dOJpQrBC+qR8-uDot25tM=XA@mail.gmail.com/#r

**Comment by lorenzolfm** [comment]
Silent Payments BIP merged
https://twitter.com/reardencode/status/1788577217884364861

**Comment by lorenzolfm** [comment]
First mainnet multi-hop asset payment w/ Taproot Asset channels
https://twitter.com/roasbeef/status/1788624974728790471

**Comment by lorenzolfm** [comment]
Bitcoin Keeper new release with Inheritance Planning, Assisted Keys, Canary Wallets, interoperability and several other key features
https://twitter.com/bitcoinKeeper_/status/1788599293152301281

**Comment by oleonardolima** [comment]
Cashu.me 0.1 – Release
https://primal.net/e/note150ywd3rmpw086uwus22kyf45gvqk78r6dl8qm4rv65jem49hglts3um34a

**Comment by oleonardolima** [comment]
bitcoin++ ecash - berlin - Oct 10 - 12, 2024
https://primal.net/e/note1msmj6unvdqnzeesafq28933nydv5wr6mfznslu0zh3gcu50td5wqxtj3tt

**Comment by oleonardolima** [comment]
Introducing Boardwalk Cash - the first dollar-based Cashu wallet built on top of #bitcoin and connected to #nostr.
https://primal.net/e/note178du87hqdtfyuflpfznq5m3lmgc3sae0ur29qda7v2fyjlzwh0nskfazq7

**Comment by lorenzolfm** [comment]
Beta release of utreexod
https://mailing-list.bitcoindevs.xyz/bitcoindev/d5f47120-3397-4f56-93ca-dd310d845f3cn@googlegroups.com/T/#u

**Comment by lorenzolfm** [comment]
Silentium - Silent payments enabled wallet
https://twitter.com/TheSingerLouis/status/1790824126472667227

**Comment by lorenzolfm** [comment]
BitScrow announces Developer Playground
https://twitter.com/BitEscrow_app/status/1791086192089329785

**Comment by oleonardolima** [comment]
Securing Git: Addressing 5 new vulnerabilities
_Git is releasing several new versions to address five CVEs. Upgrading to the latest Git version is essential to protect against these vulnerabilities._
https://github.blog/2024-05-14-securing-git-addressing-5-new-vulnerabilities/#details

**Comment by oleonardolima** [comment]
Ecash TIDES using Cashu and Stratum v2
https://delvingbitcoin.org/t/ecash-tides-using-cashu-and-stratum-v2/870/1

**Comment by oleonardolima** [comment]
Blinded Authentication Tokens in Mutiny
https://blog.mutinywallet.com/blinded-authentication/

**Comment by oleonardolima** [comment]
Silent Payments: Light Client Protocol
https://delvingbitcoin.org/t/silent-payments-light-client-protocol/891
https://github.com/setavenger/BIP0352-light-client-specification

**Comment by storopoli** [comment]
BIP de Miniscript por A. Chow

https://mailing-list.bitcoindevs.xyz/bitcoindev/0be34bd2-637b-44b1-a0d5-e0ad5812d505@achow101.com/

**Comment by storopoli** [comment]
Shouldn't we close this @lorenzolfm, @lucasdcf, @jaonoctus?
