### ISSUE TITLE
Agosto 2024

### ISSUE THREAD

**Issue by edilmedeiros** [saopaulobitdevs/saopaulobitdevs.org#34]
~~Carteira de Bitcoin da Proton
https://proton.me/blog/proton-wallet-launch
https://github.com/ProtonWallet/andromeda~~

---

[@jaonoctus] ja foi

**Comment by edilmedeiros** [comment]
A Bitaxe found a block
https://x.com/bitentrepreneur/status/1816173826754929125

**Comment by edilmedeiros** [comment]
BDK 1.0.0-beta.1
https://github.com/bitcoindevkit/bdk/releases/tag/v1.0.0-beta.1

**Comment by edilmedeiros** [comment]
Existe incentivo econômico em usar P2WSH ao invés de P2TR?
https://bitcoin.stackexchange.com/questions/123500/is-there-an-economic-incentive-to-use-p2wsh-over-p2tr

Bom tópico para iniciantes aprenderem que existem diferentes tipos de transações.

**Comment by edilmedeiros** [comment]
Por que os desevolvedores de protocolos trabalham para maximizar a receita dos mineradores?
https://bitcoin.stackexchange.com/questions/123679/why-do-protocol-developers-work-on-maximizing-miner-revenue

tl;dr não é para os mineradores, mas para os outros players da rede que não têm a mesma capacidade de prever os custos das transações.

**Comment by edilmedeiros** [comment]
Por que precisamos reestruturar a mempool para implementar o cluster mempool?
https://bitcoin.stackexchange.com/questions/123682/why-is-restructure-of-mempool-required-with-cluster-mempool

Mudanças de infraestrutura que parecem simples, mas são complexas.

**Comment by edilmedeiros** [comment]
Assinatura de transações com Yubikey
https://vxtwitter.com/Nneuman/status/1816862638900658562

**Comment by edilmedeiros** [comment]
BIP draft for the FROST threshold signing protocol
https://groups.google.com/g/bitcoindev/c/PeMp2HQl-H4

**Comment by biohazel** [comment]
Nova escola para desenvolvedoras Bitcoin somente para mulheres no Brasil, com financiamento da HRF. Aceitamos mentores voluntários de todos os gêneros para aulas, mas o Discord e eventos serão exclusivos para mulheres, seguindo a estratégia de sucesso do projeto Bitcoin Dada. https://github.com/biohazel/scalar-school-handbook

**Comment by jaonoctus** [comment]
Mutiny wallet foi de arrasta pra cima
https://blog.mutinywallet.com/mutiny-wallet-is-shutting-down/

**Comment by jaonoctus** [comment]
Vírus trocando endereços na área de transferência
https://twitter.com/SandLabs_21/status/1820311557269594463

**Comment by storopoli** [comment]
Dark Skippy is a powerful new method for a malicious signing device to leak secret keys.

https://darkskippy.com/

**Comment by biohazel** [comment]
mempoolfullrbf=1
https://x.com/peterktodd/status/1820562457015779355

**Comment by storopoli** [comment]
Testnet4 merged: https://github.com/bitcoin/bitcoin/pull/29775

**Comment by jaonoctus** [comment]
Fuzzing yet again

https://brunoerg.xyz/2024/08/12/rust-miniscript-vuln.html

**Comment by oleonardolima** [comment]
Engineering a backdoored bitcoin wallet
https://xcancel.com/wootsecurity/status/1823085045399363882
https://www.usenix.org/system/files/woot24-scott.pdf

**Comment by edilmedeiros** [comment]
Apple App Store censurando aplicativos de VPN (a mando do governo?)

https://x.com/protonvpn/status/1825181045035074016

**Comment by storopoli** [comment]
> Apple App Store censurando aplicativos de VPN (a mando do governo?)
> 
> https://x.com/protonvpn/status/1825181045035074016

Coinbase, Casa, e outros tambem censurados...

**Comment by oleonardolima** [comment]
BitVM2: Bridging Bitcoin to Second Layers
https://bitvm.org/bitvm_bridge.pdf

**Comment by oleonardolima** [comment]
[...] After a brief but intense fee spike earlier, Bitcoin Core's conservative next block fee recommendations are still stuck ~780 sats/vb.

https://xcancel.com/mononautical/status/1826679495568564677#m
https://xcancel.com/mononautical/status/1826604180251050388#m

**Comment by storopoli** [comment]
> [...] After a brief but intense fee spike earlier, Bitcoin Core's conservative next block fee recommendations are still stuck ~780 sats/vb.
> 
> https://xcancel.com/mononautical/status/1826679495568564677#m https://xcancel.com/mononautical/status/1826604180251050388#m

It was this: 
![image](https://github.com/user-attachments/assets/47a027fe-d1df-45d5-a0b3-c4ee2491aeaa)

**Comment by MPins** [comment]
New time warp vulnerability in testnet4
https://delvingbitcoin.org/t/zawy-s-alternating-timestamp-attack/1062
https://bitcoinops.org/en/newsletters/2024/08/16/

**Comment by MPins** [comment]
Onion message DoS risk discussion
https://delvingbitcoin.org/t/onion-messaging-dos-threat-mitigations/1058
https://fc24.ifca.ai/preproceedings/104.pdf

**Comment by MPins** [comment]
Bitcoin Core switch to CMake build system
https://mailing-list.bitcoindevs.xyz/bitcoindev/6cfd5a56-84b4-4cbc-a211-dd34b8942f77n@googlegroups.com/

**Comment by jaonoctus** [comment]
Mempool v3.0.0
https://x.com/mempool/status/1828057401968533629

**Comment by jaonoctus** [comment]
Zapin
https://github.com/MiguelMedeiros/zapin.me

**Comment by storopoli** [comment]
Zeus 0.9
https://github.com/ZeusLN/zeus/releases/tag/v0.9.0

**Comment by lucasdcf** [comment]
Carteira LN da Ark Labs
https://x.com/ArkLabsHQ/status/1827013390134296723

**Comment by lucasdcf** [comment]
Novo release do Floresta e technical blog post explicando as novidades
https://x.com/erik17192799/status/1825976539638288889

**Comment by lucasdcf** [comment]
Ark Release com Covenant-less Ark
https://x.com/ArkLabsHQ/status/1825542684553203722

**Comment by lucasdcf** [comment]
Backdoor em Hardware Wallet pt. 1
https://darkskippy.com/

**Comment by lucasdcf** [comment]
Backdoor em Hardware Wallet pt. 2
https://x.com/wootsecurity/status/1823085045399363882

**Comment by lucasdcf** [comment]
Mitigações Dark Skippy
https://x.com/nunchuk_io/status/1820710359780704557

**Comment by jaonoctus** [comment]
Bolt11 em C# / .NET
https://x.com/ngoline/status/1828193300546724236

**Comment by biohazel** [comment]
Bitcoin Mining Development Mailing List https://groups.google.com/g/bitcoinminingdev/about
