### ISSUE TITLE
Tópicos Agosto/2023

### ISSUE THREAD

**Issue by lorenzolfm** [saopaulobitdevs/saopaulobitdevs.org#9]
Issue reservada para proposta de tópicos para o encontro de agosto de 2023

**Comment by lorenzolfm** [comment]
"Bitcoiners are generally are unaware how weak Bitcoin’s censorship resistance becomes when the state enables deep packet inspection, protocol whitelisting at a the country level. 
The amount of work being put into traffic obfuscation technologies is severely lacking."

https://twitter.com/r32a_/status/1686916653085499392

**Comment by lorenzolfm** [comment]
https://blog.bitmex.com/drivechains/

**Comment by lorenzolfm** [comment]
Core Lightning v23.08 Release Candidate 1 https://twitter.com/Core_LN/status/1688705685285122048

**Comment by lucasdcf** [comment]
https://twitter.com/LucasNuzzi/status/1633859957434245120

**Comment by lucasdcf** [comment]
https://twitter.com/murchandamus/status/1685004407862067200

**Comment by lorenzolfm** [comment]
AI4ALL results https://twitter.com/fedibtc/status/1688617469630464000

**Comment by lorenzolfm** [comment]
If you generated a wallet using Libbitcoin's Bitcoin Explorer, including as described in the appendix to Mastering Bitcoin, your funds are at risk (or already stolen).

Full details: [https://milksad.info](https://t.co/Crlw63lUr4)

https://twitter.com/hrdng/status/1689022029142560771

**Comment by oleonardolima** [comment]
Frostsnap https://github.com/frostsnap/frostsnap
Introducing Frostsnap https://frostsnap.com/introducing-frostsnap.html

**Comment by folive3** [comment]
54% do Hashrate do Bitcoin tem KYC (Foundry +Antpool)
https://twitter.com/lasernakamoto/status/1689759526109540352?s=46&t=LrvsyosXi8wNpILTH1xIYw

**Comment by lorenzolfm** [comment]
https://stacker.news/items/234331

**Comment by oleonardolima** [comment]
Field Report: Implementing MuSig2 https://bitcoinops.org/en/newsletters/2023/08/16/
BitGo launched the first MuSig taproot multisig wallet. https://blog.bitgo.com/save-fees-with-musig2-at-bitgo-3248d690f573
Taproot Support for BitGo Wallets https://blog.bitgo.com/taproot-support-for-bitgo-wallets-9ed97f412460

**Comment by MPins** [comment]
[bitcoin-dev] BIP-352 Silent Payments addresses should have an expiration time
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2023-August/021849.html

**Comment by lucasdcf** [comment]
Serverless PayJoin
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2023-August/021868.html

**Comment by lucasdcf** [comment]
Só adicionem se alguém entender kkkk

https://blog.blockstream.com/simplicity-sharing-of-witness-and-disconnect/

**Comment by lucasdcf** [comment]
Bitcoin denominated ecash without custodial risk
https://gist.github.com/moonsettler/42b588fa97a1da3ac0adea0dd16dadf2

**Comment by lucasdcf** [comment]
Sf bitdevs colocou isso como “bitcoin adjacent”

Acho legal discutir apesar de não ser bitcoin né..

https://www.bleepingcomputer.com/news/security/new-acoustic-attack-steals-data-from-keystrokes-with-95-percent-accuracy/

https://milksad.info/

**Comment by lucasdcf** [comment]
https://blog.mutinywallet.com/enhanced-lightning-privacy-for-mutiny-users/

**Comment by lucasdcf** [comment]
Combined CTV + APO to minimal TXHASH+CSFS
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2023-August/021907.html

**Comment by lucasdcf** [comment]
impl. drivechains do luke
https://github.com/bitcoin/bitcoin/pull/28311
post Bitmex sobre drivechains
https://blog.bitmex.com/drivechains/

**Comment by lucasdcf** [comment]
Vuln. MPC
https://www.fireblocks.com/blog/bitforge-fireblocks-researchers-uncover-vulnerabilities-in-over-15-major-wallet-providers/

**Comment by lucasdcf** [comment]
cripto do BIP324
https://github.com/bitcoin/bitcoin/pull/28008

**Comment by lucasdcf** [comment]
Liquid open-source
https://blog.liquid.net/expanding-transparency-the-liquid-networks-functionary-code-is-now-open-source/

**Comment by lucasdcf** [comment]
Frost in the wild
https://x.com/machankura8333/status/1695827506794754104

**Comment by lucasdcf** [comment]
DoS: Fake LN channels
https://morehouse.github.io/lightning/fake-channel-dos

**Comment by lucasdcf** [comment]
Novo algoritmo de coinselection
https://github.com/bitcoin/bitcoin/pull/27877

**Comment by lucasdcf** [comment]
UTXO set 7.3GB
https://twitter.com/kcalvinalvinn/status/1693780164520677617

**Comment by lucasdcf** [comment]
libsecp256k1-zkp now has a draft implementation of Schnorr adaptor signatures for atomic swaps, etc.
https://twitter.com/n1ckler/status/1693650163774963946

**Comment by lucasdcf** [comment]
Private collaborative custody with FROST
https://gist.github.com/nickfarrow/4be776782bce0c12cca523cbc203fb9d
